Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-10, with the labels that each got.

#2792 Remove import from typings file
  build/typings/index.d.ts
Labels: Bug

#2791 Centralize box parsing
  src/dash/SegmentBaseLoader.js
  src/dash/utils/FragmentedTextBoxParser.js
  src/streaming/text/TextSourceBuffer.js
  src/streaming/utils/BoxParser.js
  test/unit/dash.utils.FragmentedTextBoxParser.js
  test/unit/streaming.utils.BoxParser.js
Labels: Code Refactor

#2794 Add dash.js advanced samples
  build/typings/index.d.ts
  samples/advanced/abr/LowestBitrateRule.js
  samples/advanced/abr/index.html
  samples/advanced/extend.html
  samples/advanced/listening-to-SCTE-EMSG-events.html
  samples/advanced/monitoring.html
  samples/audio-only/index.html
  samples/samples.json
Labels: Documentation

#2787 Update unit tests
  src/mss/MssFragmentMoovProcessor.js
  src/mss/MssHandler.js
  src/mss/errors/MssErrors.js
  test/unit/dash.DashAdapter.js
  test/unit/dash.DashHandlerSpec.js
  test/unit/dash.DashMetrics.js
  test/unit/dash.controllers.RepresentationControllerSpec.js
  test/unit/dash.models.DashManifestModel.js
  test/unit/dash.utils.SegmentUtils.js
  test/unit/dash.utils.TimelineConverter.js
  test/unit/dash.utils.TimelineSegmentsGetter.js
  test/unit/helpers/ObjectsHelper.js
  test/unit/mocks/AbrControllerMock.js
  test/unit/mocks/DashManifestModelMock.js
  test/unit/mocks/RepresentationControllerMock.js
  test/unit/mocks/StreamProcessorMock.js
  test/unit/mocks/TextControllerMock.js
  test/unit/mocks/TextSourceBufferMock.js
  test/unit/mocks/ThroughputHistoryMock.js
  test/unit/mss.MssFragmentProcessor.js
  test/unit/mss.errors.MssErrors.js
  test/unit/mss.parser.MssParser.js
  test/unit/streaming.controllers.BufferControllerSpec.js
  test/unit/streaming.controllers.FragmentControllerSpec.js
  test/unit/streaming.controllers.SourceBufferSink.js
  test/unit/streaming.thumbnail.ThumbnailController.js
  test/unit/streaming.utils.BasicSelector.js
  test/unit/streaming.utils.DVBSelector.js
Labels: Unit Testing

#2784 SegmentBase fragmented thumbnail implementation and example
  contrib/akamai/controlbar/ControlBar.js
  samples/dash-if-reference-player/app/sources.json
  src/streaming/MediaPlayer.js
  src/streaming/Stream.js
  src/streaming/thumbnail/ThumbnailController.js
  src/streaming/thumbnail/ThumbnailTracks.js
  test/unit/streaming.thumbnail.ThumbnailController.js
Labels: Feature Enhancement

#2798 Allow easy testing of player API in Ref Player
  samples/dash-if-reference-player/app/main.js
Labels: Reference Player

#2800 BUGFIX: Clean-up CDM key sessions when videoelement unref'ed.
  src/streaming/protection/models/ProtectionModel_01b.js
Labels: EME/DRM

#2799 Clean and refactoring
  src/streaming/MediaPlayer.js
  src/streaming/PreBufferSink.js
  src/streaming/SourceBufferSink.js
  src/streaming/StreamProcessor.js
  src/streaming/constants/Constants.js
  src/streaming/controllers/AbrController.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/models/MediaPlayerModel.js
  src/streaming/models/VideoModel.js
  src/streaming/rules/SwitchRequest.js
  src/streaming/text/EmbeddedTextHtmlRender.js
  src/streaming/thumbnail/ThumbnailController.js
  src/streaming/utils/TTMLParser.js
  test/unit/mocks/MediaPlayerModelMock.js
  test/unit/mocks/URIFragmentModelMock.js
  test/unit/streaming.MediaPlayerSpec.js
  test/unit/streaming.constants.Constants.js
  test/unit/streaming.controllers.AbrControllerSpec.js
  test/unit/streaming.controllers.PlaybackControllers.js
  test/unit/streaming.models.MediaPlayerModel.js
Labels: Code Refactor

#2808 Add retry mechanism to license HTTP requests
  src/streaming/protection/controllers/ProtectionController.js
Labels: EME/DRM

#2788 Errors type script + JSDoc comments
  index.d.ts
  src/core/errors/Errors.js
  src/mss/errors/MssErrors.js
  src/streaming/protection/errors/ProtectionErrors.js
  src/streaming/utils/ErrorHandler.js
Labels: Documentation

#2811 Add timeout config for license requests
  samples/dash-if-reference-player/app/sources.json
  src/streaming/protection/controllers/ProtectionController.js
Labels: EME/DRM

#2817 remove deprecated livestream from samples
  samples/dash-if-reference-player/app/sources.json
Labels: Reference Player

#2813 Low latency improvements
  .gitignore
  index.d.ts
  samples/dash-if-reference-player/app/main.js
  samples/dash-if-reference-player/app/sources.json
  src/dash/utils/TemplateSegmentsGetter.js
  src/dash/utils/TimelineConverter.js
  src/streaming/FragmentLoader.js
  src/streaming/MediaPlayer.js
  src/streaming/MediaPlayerEvents.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/TimeSyncController.js
  src/streaming/models/MediaPlayerModel.js
  src/streaming/models/MetricsModel.js
  src/streaming/net/FetchLoader.js
  src/streaming/net/HTTPLoader.js
  src/streaming/net/XHRLoader.js
  src/streaming/rules/ThroughputHistory.js
  src/streaming/rules/abr/InsufficientBufferRule.js
  src/streaming/rules/abr/SwitchHistoryRule.js
  src/streaming/rules/abr/ThroughputRule.js
  src/streaming/rules/scheduling/NextFragmentRequestRule.js
  src/streaming/utils/SupervisorTools.js
  test/unit/mocks/MediaPlayerModelMock.js
  test/unit/mocks/PlaybackControllerMock.js
  test/unit/streaming.MediaPlayerSpec.js
  test/unit/streaming.controllers.PlaybackControllers.js
  test/unit/streaming.models.MediaPlayerModel.js
Labels: Feature request from DASH IF IOP

#2831 Limit time threshold for segment request calculation
  src/streaming/models/FragmentModel.js
Labels: Regression

#2832 Remove not working samples
  samples/dash-if-reference-player/app/sources.json
Labels: Reference Player

#2830 Update demo sample page
  samples/dash-if-reference-player/app/main.js
  samples/dash-if-reference-player/index.html
Labels: Reference Player

#2826 Fix about Event_asArray attribute
  src/dash/models/DashManifestModel.js
Labels: Bug

#2823 Fixing a couple of broken links in the contributing doc
  CONTRIBUTING.md
Labels: Documentation

#2839 Update index.d.ts
  index.d.ts
Labels: Documentation
