Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-09, with the labels that each got.

#2761 Fix ProtectionModel_21Jan2015
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: EME/DRM

#2770 Restore issue fixing in PR#2318
  src/streaming/protection/controllers/ProtectionKeyController.js
Labels: Regression

#2773 Update TypeScript definition
  build/typings/index.d.ts
  index.d.ts
Labels: Documentation

#2777 Fix scheduleWhilePaused behavior
  src/streaming/controllers/ScheduleController.js
Labels: Bug

#2764 New Refactoring
  src/dash/DashAdapter.js
  src/dash/DashHandler.js
  src/dash/models/DashManifestModel.js
  src/dash/utils/TimelineSegmentsGetter.js
  src/mss/MssHandler.js
  src/streaming/MediaPlayer.js
  src/streaming/Stream.js
  src/streaming/StreamProcessor.js
  src/streaming/controllers/AbrController.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/controllers/StreamController.js
  src/streaming/models/MediaPlayerModel.js
  src/streaming/models/VideoModel.js
  src/streaming/rules/ThroughputHistory.js
  test/unit/mocks/MediaPlayerModelMock.js
  test/unit/mocks/StreamControllerMock.js
  test/unit/streaming.MediaPlayerSpec.js
  test/unit/streaming.Stream.js
  test/unit/streaming.controllers.AbrControllerSpec.js
  test/unit/streaming.controllers.ScheduleController.js
  test/unit/streaming.controllers.StreamController.js
Labels: Code Refactor

#2778 Use threshold in removeExecutedRequestsAfterTime
  src/streaming/controllers/ScheduleController.js
  src/streaming/models/FragmentModel.js
Labels: Bug

#2783 Add missing errors management
  src/mss/MssFragmentMoofProcessor.js
  src/streaming/ManifestUpdater.js
  src/streaming/Stream.js
  src/streaming/controllers/StreamController.js
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/protection/errors/ProtectionErrors.js
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
  test/unit/dash.DashParser.js
  test/unit/data/dash/manifest_error.xml
  test/unit/mocks/ErrorHandlerMock.js
  test/unit/mocks/ProtectionModelMock.js
  test/unit/mss.MssFragmentProcessor.js
  test/unit/streaming.ManifestUpdater.js
  test/unit/streaming.Stream.js
  test/unit/streaming.protection.controllers.ProtectionController.js
  test/unit/streaming.protection.errors.ProtectionErrors.js
Labels: Feature Enhancement

#2785 Fix issue with captions and subs atom box
  src/dash/utils/FragmentedTextBoxParser.js
  src/streaming/text/TextSourceBuffer.js
Labels: Bug
