Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-03, with the labels that each got.

#2444 New TTML_PARSED event
  index.d.ts
  src/streaming/MediaPlayerEvents.js
  src/streaming/utils/TTMLParser.js
Labels: Feature Enhancement

#2450 Add support for MultiKey DRM
  samples/dash-if-reference-player/app/sources.json
  samples/protection/getLicense.html
  src/streaming/MediaPlayer.js
  src/streaming/Stream.js
  src/streaming/protection/Protection.js
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: EME/DRM

#2274 Allow preload of Dash media without a video element
  index.d.ts
  samples/getting-started-basic-embed/pre-load-video.html
  samples/index.html
  src/core/events/CoreEvents.js
  src/dash/DashHandler.js
  src/streaming/FragmentSink.js
  src/streaming/MediaPlayer.js
  src/streaming/PreBufferSink.js
  src/streaming/SourceBufferSink.js
  src/streaming/Stream.js
  src/streaming/StreamProcessor.js
  src/streaming/controllers/AbrController.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/MediaSourceController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/controllers/SourceBufferController.js
  src/streaming/controllers/StreamController.js
  src/streaming/models/VideoModel.js
  src/streaming/rules/scheduling/NextFragmentRequestRule.js
  src/streaming/text/NotFragmentedTextBufferController.js
  src/streaming/text/TextBufferController.js
  test/unit/mocks/MediaSourceBufferMock.js
  test/unit/mocks/MediaSourceMock.js
  test/unit/mocks/SourceBufferControllerMock.js
  test/unit/mocks/StreamControllerMock.js
  test/unit/mocks/StreamProcessorMock.js
  test/unit/mocks/TextBufferMock.js
  test/unit/mocks/TextControllerMock.js
  test/unit/streaming.MediaPlayerSpec.js
  test/unit/streaming.controllers.BufferControllerSpec.js
  test/unit/streaming.controllers.PreBufferSink.js
  test/unit/streaming.controllers.SourceBufferController.js
  test/unit/streaming.controllers.SourceBufferSink.js
  test/unit/streaming.text.NotFragmentedTextBufferController.js
  test/unit/streaming.text.TextBufferController.js
Labels: Feature Enhancement

#2456 Protection Data to accept changes before Protection initialization
  src/streaming/MediaPlayer.js
  src/streaming/controllers/StreamController.js
Labels: EME/DRM

#2459 Check streamprocessors while initializing protection
  src/streaming/Stream.js
  src/streaming/controllers/StreamController.js
Labels: Regression

#2452 Revert ProtectionController
  src/streaming/protection/controllers/ProtectionController.js
Labels: EME/DRM

#2464 Fix SeekBar style (ControlBar)
  contrib/akamai/controlbar/controlbar.css
  contrib/akamai/controlbar/snippet.html
  samples/dash-if-reference-player/index.html
Labels: Reference Player

#2467 Vtt subtitles bug fix
  src/streaming/text/NotFragmentedTextBufferController.js
  src/streaming/text/TextBufferController.js
Labels: Regression

#2433 onManifestUpdated and getStreamsInfo optimizations
  src/dash/DashAdapter.js
  src/streaming/MediaPlayer.js
  src/streaming/controllers/StreamController.js
Labels: Code Refactor

#2473 Fix creation of buffers
  src/streaming/Stream.js
Labels: Bug

#2474 Management of DRM license with an expiration value
  samples/dash-if-reference-player/app/sources.json
  src/streaming/Stream.js
  src/streaming/protection/ProtectionEvents.js
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: EME/DRM

#2465 improve track switch process
  src/dash/models/DashManifestModel.js
  src/streaming/Stream.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/ScheduleController.js
Labels: Feature Enhancement

#2466 Simplification of factory management
  src/core/FactoryMaker.js
Labels: Code Refactor

#2485 #2477 remove xhr.status check before triggering LOADING_ABANDONED event in FragmentLoader
  src/streaming/FragmentLoader.js
  src/streaming/XHRLoader.js
  test/unit/streaming.XHRLoader.js
Labels: Bug

#2469 Shift caption start time by MSETimeOffset * videoTimescale
  src/streaming/text/TextSourceBuffer.js
Labels: Bug
