Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-11, with the labels that each got.

#2827 Fix ClearKey issue
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: EME/DRM

#2846 ClearKey regression fix
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: Regression

#2853 update conformance tool url
  ISSUE_TEMPLATE.md
Labels: Documentation

#2852 Multiperiod transition logic changes
  src/streaming/SourceBufferSink.js
  src/streaming/Stream.js
  src/streaming/controllers/StreamController.js
  test/unit/streaming.Stream.js
Labels: Feature Enhancement

#2835 Reset on edge bug fix
  src/streaming/controllers/PlaybackController.js
Labels: Awaiting Feedback

#2836 HTTPLoader abort()
  src/streaming/net/HTTPLoader.js
Labels: Bug

#2870 parseFloat bug fix
  src/streaming/controllers/BufferController.js
Labels: Bug
