Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-08, with the labels that each got.

#2726 Fixed error in index.d.ts.
  build/typings/index.d.ts
  index.d.ts
Labels: Documentation

#2736 Change URLs from vm2.dashif.org to livesim.dashif.org
  samples/dash-if-reference-player/app/sources.json
Labels: Reference Player

#2739 Add support for emsg boxes version 1
  package-lock.json
  package.json
  src/streaming/vo/IsoBox.js
Labels: Feature Enhancement

#2738 Polish dash.js samples
  samples/audio-only/index.html
  samples/getting-started/listening-to-SCTE-EMSG-events.html
  samples/highlighter.js
  samples/samples.json
Labels: Documentation

#2733 Math.trunc not supported by IE11
  src/streaming/controllers/TimeSyncController.js
Labels: Bug

#2742 Update unit tests
  src/streaming/Stream.js
  src/streaming/rules/scheduling/BufferLevelRule.js
  src/streaming/thumbnail/ThumbnailController.js
  src/streaming/thumbnail/ThumbnailTracks.js
  test/unit/mocks/StreamProcessorMock.js
  test/unit/mocks/TextControllerMock.js
  test/unit/streaming.Stream.js
  test/unit/streaming.rules.scheduling.BufferLevelRule.js
  test/unit/streaming.thumbnail.ThumbnailController.js
Labels: Unit Testing

#2743 Refactoring branch
  src/dash/DashAdapter.js
  src/dash/DashHandler.js
  src/dash/controllers/RepresentationController.js
  src/dash/models/DashManifestModel.js
  src/streaming/Stream.js
  src/streaming/StreamProcessor.js
  src/streaming/controllers/AbrController.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/EventController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/rules/RulesContext.js
  src/streaming/rules/scheduling/BufferLevelRule.js
  src/streaming/rules/scheduling/NextFragmentRequestRule.js
  src/streaming/text/NotFragmentedTextBufferController.js
  src/streaming/text/TextSourceBuffer.js
  src/streaming/utils/LiveEdgeFinder.js
  test/unit/dash.DashAdapter.js
  test/unit/dash.controllers.RepresentationControllerSpec.js
  test/unit/dash.models.DashManifestModel.js
  test/unit/mocks/AdapterMock.js
  test/unit/mocks/StreamProcessorMock.js
  test/unit/streaming.controllers.EventController.js
Labels: Code Refactor
