Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-02, with the labels that each got.

#2413 Protect seek function
  contrib/akamai/controlbar/ControlBar.js
  src/streaming/MediaPlayer.js
  test/unit/streaming.MediaPlayerSpec.js
Labels: Feature Enhancement

#2414 Update type definitions
  build/typings/index.d.ts
  index.d.ts
Labels: Bug

#2412 Move diagrams to docs folder
  docs/diagrams/ABRRuleCollection.pdf
  docs/diagrams/ABRRulesCollection.uml
  docs/diagrams/FragmentLoader.pdf
  docs/diagrams/FragmentLoader.uml
  docs/diagrams/ManifestLoader.pdf
  docs/diagrams/ManifestLoader.uml
  docs/diagrams/MediaPlayer.pdf
  docs/diagrams/MediaPlayer.uml
  docs/diagrams/MediaPlayerModel.pdf
  docs/diagrams/MediaPlayerModel.uml
  docs/diagrams/MetricsModel.pdf
  docs/diagrams/MetricsModel.uml
  docs/diagrams/Stream.pdf
  docs/diagrams/Stream.uml
  docs/diagrams/StreamController.pdf
  docs/diagrams/StreamController.uml
  docs/diagrams/StreamProcessor.pdf
  docs/diagrams/StreamProcessor.uml
  docs/diagrams/XHRLoader.pdf
  docs/diagrams/XHRLoader.uml
  docs/diagrams/XLinkLoader.pdf
  docs/diagrams/XLinkLoader.uml
  samples/diagrams/diagram.pdf
Labels: Documentation

#2416 update track switch mode for audio and video
  samples/dash-if-reference-player/app/main.js
  samples/dash-if-reference-player/index.html
Labels: Reference Player

#2419 Add buffer level bar to control bar
  contrib/akamai/controlbar/ControlBar.js
  contrib/akamai/controlbar/controlbar.css
  contrib/akamai/controlbar/snippet.html
  samples/chromecast/receiver/js/main.js
  samples/dash-if-reference-player/index.html
Labels: Reference Player

#2420 Allow buffer removal when MediaSource is ended
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/SourceBufferController.js
Labels: Bug

#2351 Improve seek velocity
  src/streaming/controllers/ScheduleController.js
Labels: Feature Enhancement

#2418 Jump gaps feature
  index.d.ts
  samples/dash-if-reference-player/app/css/main.css
  samples/dash-if-reference-player/app/main.js
  samples/dash-if-reference-player/index.html
  src/streaming/MediaPlayer.js
  src/streaming/controllers/StreamController.js
  src/streaming/models/MediaPlayerModel.js
  test/unit/mocks/MediaPlayerModelMock.js
  test/unit/streaming.MediaPlayerSpec.js
Labels: Feature Enhancement

#2426 hasInitialization must return true if there is an initialization range
  src/dash/vo/Representation.js
Labels: Regression

#2397 [MSS] Widevine pssh generation
  externals/base64.js
  src/mss/parser/MssParser.js
  src/streaming/protection/drm/KeySystemWidevine.js
Labels: EME/DRM

#2398 Use protection module without video element
  build/typings/index.d.ts
  index.d.ts
  samples/protection/getLicense.html
  src/streaming/MediaPlayer.js
  src/streaming/protection/Protection.js
  src/streaming/protection/ProtectionEvents.js
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: EME/DRM

#2436 Overwrite initData when user provided parameters for generating it
  src/streaming/Stream.js
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/utils/ErrorHandler.js
Labels: EME/DRM

#2437 Improve audio switch
  src/streaming/StreamProcessor.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/models/FragmentModel.js
  src/streaming/rules/scheduling/NextFragmentRequestRule.js
Labels: Feature Enhancement

#2435 Add DRM error for insecure origin
  src/streaming/protection/Protection.js
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: EME/DRM

#2446 Fix #2445
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: Regression
