Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-04, with the labels that each got.

#2505 add TTML_TO_PARSE event
  src/mss/MssHandler.js
  src/streaming/MediaPlayerEvents.js
  src/streaming/utils/TTMLParser.js
Labels: Feature Enhancement

#2451 Load persistent sessions
  samples/dash-if-reference-player/app/main.js
  samples/dash-if-reference-player/app/sources.json
  samples/dash-if-reference-player/index.html
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/protection/controllers/ProtectionKeyController.js
  src/streaming/protection/drm/KeySystem.js
  src/streaming/protection/drm/KeySystemClearKey.js
  src/streaming/protection/drm/KeySystemPlayReady.js
  src/streaming/protection/drm/KeySystemW3CClearKey.js
  src/streaming/protection/drm/KeySystemWidevine.js
  src/streaming/protection/models/ProtectionModel.js
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: EME/DRM

#2523 Use embeddedTimescale for CEA608 instead of timescale in MPD
  src/streaming/text/TextSourceBuffer.js
Labels: Regression

#2526 Added Axinom Live-Clear reference stream
  samples/dash-if-reference-player/app/sources.json
Labels: Reference Player

#2520 Added resolution to bitrate list in the controlbar
  contrib/akamai/controlbar/ControlBar.js
  contrib/akamai/controlbar/controlbar.css
Labels: Feature Enhancement, Reference Player

#2447 getRepresentationsForAdaptation optimization
  src/dash/models/DashManifestModel.js
  src/streaming/controllers/StreamController.js
Labels: Code Refactor

#2475 Optimization of track addition
  src/streaming/Stream.js
  src/streaming/controllers/MediaController.js
Labels: Code Refactor

#2544 Revert PR #2531
  src/streaming/models/FragmentModel.js
Labels: Regression

#2548 Fix #2547 - do not reject empty TTML docs as invalid
  src/streaming/utils/TTMLParser.js
Labels: Regression

#2555 Add note to live latency description
  samples/dash-if-reference-player/index.html
Labels: Reference Player

#2553 Adding sample to show SCTE EMSG event capture from a live stream
  samples/getting-started-basic-embed/listening-to-SCTE-EMSG-events.html
Labels: Documentation

#2557 MSS create datachunk now supports endFragment parameter
  src/mss/MssHandler.js
Labels: Regression

#2558 Fix clearNextRange so it checks buffer properly
  samples/dash-if-reference-player/app/sources.json
  src/streaming/controllers/BufferController.js
Labels: Regression
