Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-07, with the labels that each got.

#2677 Fix low latency API
  build/typings/index.d.ts
  index.d.ts
  samples/dash-if-reference-player/app/main.js
  src/streaming/MediaPlayer.js
  src/streaming/models/MediaPlayerModel.js
  test/unit/streaming.models.MediaPlayerModel.js
Labels: Documentation, Feature Enhancement

#2675 Control bar and logging examples
  samples/control/controlbar.html
  samples/control/logging.html
  samples/index.html
  samples/samples.json
Labels: Documentation

#2673 pass distinctiveIdentifier and persistentState through to CDM
  src/streaming/protection/controllers/ProtectionController.js
Labels: EME/DRM

#2713 Fix #2700 - Load the Message Data for EventStream Events
  src/dash/models/DashManifestModel.js
Labels: Feature Enhancement

#2710 Fixes a crash when a network error happened, but status code was 200
  src/streaming/net/FetchLoader.js
  src/streaming/net/HTTPLoader.js
Labels: Bug

#2717 Internal seek update
  src/streaming/controllers/PlaybackController.js
Labels: Bug

#2716 End detection bug fix
  src/streaming/controllers/MediaSourceController.js
  src/streaming/controllers/ScheduleController.js
Labels: Bug

#2706 Refactoring branch
  src/dash/DashAdapter.js
  src/dash/DashHandler.js
  src/streaming/MediaPlayer.js
  src/streaming/Stream.js
  src/streaming/controllers/MediaController.js
  src/streaming/text/TextTracks.js
  test/unit/dash.DashAdapter.js
  test/unit/dash.DashHandlerSpec.js
  test/unit/mocks/AdapterMock.js
  test/unit/mocks/DashManifestModelMock.js
  test/unit/mocks/StreamMock.js
  test/unit/streaming.controllers.MediaController.js
  test/unit/streaming.text.TextController.js
  test/unit/streaming.thumbnail.ThumbnailController.js
Labels: Code Refactor

#2718 Add support for MSS start-over streams
  src/mss/MssFragmentInfoController.js
  src/mss/MssFragmentMoofProcessor.js
  src/mss/MssFragmentProcessor.js
  src/mss/MssHandler.js
  src/mss/parser/MssParser.js
  src/streaming/MediaPlayer.js
  src/streaming/controllers/StreamController.js
Labels: MSS

#2665 Keep media keys
  build/typings/index.d.ts
  index.d.ts
  src/streaming/MediaPlayer.js
  src/streaming/models/MediaPlayerModel.js
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/protection/models/ProtectionModel_01b.js
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
  src/streaming/protection/models/ProtectionModel_3Feb2014.js
Labels: EME/DRM

#2691 Subtitles bugfix
  src/dash/DashAdapter.js
  src/dash/DashHandler.js
  src/streaming/Stream.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/MediaController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/rules/scheduling/NextFragmentRequestRule.js
  src/streaming/text/TextController.js
  src/streaming/text/TextSourceBuffer.js
  test/unit/mocks/ErrorHandlerMock.js
  test/unit/streaming.text.TextSourceBuffer.js
Labels: Bug

#2669 Protection Controller onNeedKey will be delayed until initializeForMedia is called
  src/streaming/protection/controllers/ProtectionController.js
Labels: EME/DRM

#2676 Fix to update liveEdge in every segment list update
  src/dash/DashHandler.js
Labels: Feature Enhancement
