Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-05, with the labels that each got.

#2554 PlayReady DRM fixes for SmartTVs
  src/dash/DashAdapter.js
  src/dash/models/DashManifestModel.js
  src/streaming/ManifestLoader.js
  src/streaming/controllers/TimeSyncController.js
  src/streaming/protection/drm/KeySystemPlayReady.js
  src/streaming/protection/models/ProtectionModel_01b.js
  src/streaming/rules/scheduling/BufferLevelRule.js
  src/streaming/utils/CustomTimeRanges.js
Labels: EME/DRM

#2492 Fix instantiation of extensions
  src/core/FactoryMaker.js
Labels: Code Refactor

#2462 Clean URIQueryAndFragmentModel
  src/streaming/MediaPlayer.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/models/URIFragmentModel.js
Labels: Code Refactor

#2494 Add correct support of audio element
  src/streaming/MediaPlayer.js
  src/streaming/Stream.js
  src/streaming/models/VideoModel.js
  src/streaming/rules/DroppedFramesHistory.js
  test/unit/mocks/VideoElementMock.js
  test/unit/streaming.MediaPlayerSpec.js
Labels: Dash Face 2 Face Action Item

#2453 Optimization of manifest processing (ObjectIron)
  externals/objectiron.js
  src/dash/parser/DashParser.js
  src/dash/parser/maps/CommonProperty.js
  src/dash/parser/maps/MapNode.js
  src/dash/parser/objectiron.js
  test/unit/dash.parser.maps.CommonProperty.js
  test/unit/dash.parser.maps.MapNode.js
Labels: Code Refactor, Dash Face 2 Face Action Item

#2573 Introduce new API enableForcedTextStreaming
  src/streaming/MediaPlayer.js
  src/streaming/controllers/BufferController.js
  src/streaming/rules/scheduling/BufferLevelRule.js
  src/streaming/rules/scheduling/NextFragmentRequestRule.js
  src/streaming/text/TextController.js
Labels: Feature Enhancement

#2571 don't double-add caption parsers on period switch
  src/streaming/text/TextSourceBuffer.js
Labels: Bug

#2582 Update TextTrack creation
  src/streaming/text/TextTracks.js
Labels: Bug

#2586 Fix couple of race conditions when resetting while loading
  src/streaming/ManifestLoader.js
  src/streaming/controllers/StreamController.js
Labels: Bug

#2545 Redundant segment download when changing quality
  src/streaming/models/FragmentModel.js
Labels: Bug

#2581 Safari/Mac live stream fail fix
  src/streaming/SourceBufferSink.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/models/FragmentModel.js
Labels: Bug

#2590 Low latency stuck on start fix
  src/streaming/controllers/BufferController.js
Labels: Bug

#2598 Don't listen to events coming from aborted XmlHTTPRequests
  src/streaming/net/XHRLoader.js
  test/unit/streaming.net.XHRLoader.js
Labels: Bug
