Repository Dash-Industry-Forum/dash.js, pull requests merged in 2018-06, with the labels that each got.

#2608 Case insensitive comparison for nodeName
  src/streaming/MediaPlayerFactory.js
  src/streaming/Stream.js
  src/streaming/models/VideoModel.js
Labels: Regression

#2614 add accessibility to TextTrackInfo
  src/streaming/text/TextSourceBuffer.js
Labels: Feature Enhancement

#2618 Fix functional tests
  test/functional/config/streams.json
  test/functional/tests.html
Labels: Automation

#2611 Fixed a bug in playbackController causing multiple wallclockTime intervals
  src/streaming/controllers/PlaybackController.js
Labels: Bug

#2619 Make more robust the period parsing. Add unit tests
  src/dash/models/DashManifestModel.js
  src/streaming/MediaPlayer.js
  src/streaming/protection/drm/KeySystemW3CClearKey.js
  src/streaming/text/TextSourceBuffer.js
  src/streaming/utils/DOMStorage.js
  src/streaming/utils/TTMLParser.js
  test/unit/dash.models.DashManifestModel.js
  test/unit/streaming.protection.drm.KeySystemW3CClearKey.js
Labels: Code Refactor

#2623 Functional tests improvements to make them work in IE/Edge
  Gruntfile.js
  test/functional/config/applications.js
  test/functional/config/browsers/windows.js
  test/functional/config/streams.json
  test/functional/config/testsConfig.js
  test/functional/tests/play/pause.js
  test/functional/tests/play/seek.js
  test/functional/tests/player_functions.js
  test/functional/tests/tests_functions.js
Labels: Automation

#2624 Removed IE from functional tests, it crashes often
  .travis.yml
  test/functional/config/browsers/windows.js
  test/functional/tools/Win10nodeConfig.json
Labels: Automation

#2595 Wait until buffer is ready when changing timestamp offset
  src/streaming/PreBufferSink.js
  src/streaming/SourceBufferSink.js
  src/streaming/controllers/BufferController.js
  src/streaming/text/NotFragmentedTextBufferController.js
  src/streaming/text/TextBufferController.js
  test/unit/mocks/MediaSourceBufferMock.js
Labels: Bug

#2605 Low latency catch up
  build/typings/index.d.ts
  index.d.ts
  samples/dash-if-reference-player/app/sources.json
  src/streaming/MediaPlayer.js
  src/streaming/MediaPlayerEvents.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/rules/scheduling/BufferLevelRule.js
  test/unit/mocks/PlaybackControllerMock.js
  test/unit/streaming.MediaPlayerSpec.js
Labels: Feature Enhancement

#2628 Fix #2627
  src/streaming/protection/models/ProtectionModel_3Feb2014.js
Labels: Bug

#2633 Fix subtitles in multiple period
  build/typings/index.d.ts
  src/streaming/SourceBufferSink.js
  src/streaming/text/TextController.js
  src/streaming/text/TextSourceBuffer.js
Labels: Bug

#2610 Update not fragmented subtitles management
  src/streaming/Stream.js
  src/streaming/StreamProcessor.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/text/NotFragmentedTextBufferController.js
  src/streaming/text/TextBufferController.js
  src/streaming/text/TextController.js
  src/streaming/text/TextSourceBuffer.js
  test/unit/mocks/StreamControllerMock.js
  test/unit/streaming.text.NotFragmentedTextBufferController.js
  test/unit/streaming.text.TextController.js
Labels: Feature Enhancement

#2635 Update sources.json
  samples/dash-if-reference-player/app/sources.json
Labels: Reference Player

#2638 Fix issue in MediaPlayerFactory related with the new logging system
  src/streaming/MediaPlayerFactory.js
Labels: Regression

#2648 Fixed crash when calling attachView on an already initialized player
  src/streaming/controllers/StreamController.js
Labels: Bug

#2645 Fix LOADING_PROGRESS event not being fired
  src/streaming/FragmentLoader.js
  src/streaming/net/HTTPLoader.js
Labels: Bug

#2649 send proper field to Cea608Parser
  src/streaming/text/TextSourceBuffer.js
Labels: Bug

#2646 Removed the buffer append queue control from BufferController
  src/streaming/controllers/BufferController.js
Labels: Bug

#2580 Smooth period transition
  src/streaming/SourceBufferSink.js
  src/streaming/Stream.js
  src/streaming/StreamProcessor.js
  src/streaming/controllers/AbrController.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/controllers/StreamController.js
  src/streaming/models/FragmentModel.js
  src/streaming/models/VideoModel.js
  src/streaming/text/NotFragmentedTextBufferController.js
  test/unit/mocks/TextBufferMock.js
Labels: Feature request from DASH IF IOP

#2622 PlaybackController will end the stream if it's unfinished
  src/streaming/controllers/PlaybackController.js
Labels: Bug

#2636 Reorganization of Dash.js Samples
  package-lock.json
  samples/audio-only/index.html
  samples/captioning/caption_vtt.html
  samples/captioning/multi-track-captions.html
  samples/captioning/ttml-ebutt-sample.html
  samples/drm/clearkey.html
  samples/drm/playready.html
  samples/drm/widevine.html
  samples/getting-started/auto-load-multi-video.html
  samples/getting-started/auto-load-single-video-src.html
  samples/getting-started/auto-load-single-video-with-context-and-source.html
  samples/getting-started/auto-load-single-video-with-reference.html
  samples/getting-started/auto-load-single-video.html
  samples/getting-started/listening-to-SCTE-EMSG-events.html
  samples/getting-started/listening-to-events.html
  samples/getting-started/manual-load-single-video.html
  samples/getting-started/manual-load-with-custom-settings.html
  samples/getting-started/pre-load-video.html
  samples/highlighter.js
  samples/index.html
  samples/live-streaming/live-delay-comparison-custom-manifest.html
  samples/live-streaming/live-delay-comparison-using-fragmentCount.html
  samples/low-latency/index.html
  samples/monitoring/index.html
  samples/multiperiod/index.html
  samples/samples.json
  samples/smooth-streaming/mss.html
  samples/thumbnails/thumbnails.html
Labels: Documentation

#2657 Fixes PLAYBACK_ENDED stopping streams after first period
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/StreamController.js
  test/unit/streaming.controllers.PlaybackControllers.js
Labels: Regression

#2652 Low latency improvements
  samples/dash-if-reference-player/app/sources.json
  src/streaming/MediaPlayer.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/controllers/TimeSyncController.js
  src/streaming/models/MediaPlayerModel.js
  src/streaming/net/FetchLoader.js
  src/streaming/net/HTTPLoader.js
  src/streaming/rules/ThroughputHistory.js
  test/unit/streaming.controllers.BufferControllerSpec.js
  test/unit/streaming.net.FetchLoader.js
Labels: Feature Enhancement

#2672 Add internal seek
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/ScheduleController.js
Labels: Regression

#2666 Fix stalling after seeking
  src/streaming/SourceBufferSink.js
Labels: Regression

#2678 Fix regression due to internal seek
  src/streaming/controllers/BufferController.js
Labels: Regression

#2680 Removed isInBuffer check
  src/streaming/models/FragmentModel.js
Labels: Regression
