Repository Dash-Industry-Forum/dash.js, pull requests merged in 2019-11, with the labels that each got.

#3110 Add thumbnail support for SegmentTimeline representation
  samples/dash-if-reference-player/app/sources.json
  src/streaming/thumbnail/ThumbnailController.js
  src/streaming/thumbnail/ThumbnailTracks.js
  test/unit/streaming.thumbnail.ThumbnailController.js
Labels: Feature Enhancement

#3109 [MSS] fix missing DVRWindowLength for live streams
  src/mss/parser/MssParser.js
Labels: Bug, MSS

#3108 Fix abandon switch request if min bit rate is set
  src/streaming/rules/abr/AbandonRequestsRule.js
Labels: Bug

#3107 Key system priority
  index.d.ts
  src/streaming/protection/controllers/ProtectionController.js
Labels: EME/DRM, Feature Enhancement

#3112 Add segment quality in HTTPRequest metrics
  src/dash/DashMetrics.js
  src/streaming/models/MetricsModel.js
  src/streaming/vo/metrics/HTTPRequest.js
Labels: Feature Enhancement
