Repository Dash-Industry-Forum/dash.js, pull requests merged in 2019-02, with the labels that each got.

#2929 Parse label from DASH manifest AdaptationSet
  contrib/akamai/controlbar/ControlBar.js
  index.d.ts
  src/dash/DashAdapter.js
  src/dash/models/DashManifestModel.js
  src/streaming/text/TextController.js
  src/streaming/text/TextSourceBuffer.js
  src/streaming/text/TextTracks.js
Labels: Feature Enhancement

#2933 [MSS] Correct minBufferTime setting
  src/mss/parser/MssParser.js
Labels: MSS

#2935 checkPortalSize function required Math.abs when calculating the Representation with nearest Width to the elementWidth
  src/streaming/controllers/AbrController.js
Labels: Awaiting Feedback
