Repository Dash-Industry-Forum/dash.js, pull requests merged in 2019-04, with the labels that each got.

#2967 Fix bug when parsing range of initialization segment
  src/dash/models/DashManifestModel.js
Labels: Bug

#2953 Add possibility to filter and reorder key systems prioritization order at application level
  index.d.ts
  src/streaming/protection/controllers/ProtectionController.js
  src/streaming/protection/controllers/ProtectionKeyController.js
Labels: EME/DRM

#2960 Added live indicator to controlbar.
  contrib/akamai/controlbar/ControlBar.js
  contrib/akamai/controlbar/controlbar.css
Labels: Reference Player

#2971 Audio Bug fix
  src/dash/DashMetrics.js
  src/streaming/Stream.js
Labels: Regression
