Repository Dash-Industry-Forum/dash.js, pull requests merged in 2019-01, with the labels that each got.

#2714 Edge licenses persistence
  samples/dash-if-reference-player/app/main.js
  samples/dash-if-reference-player/app/sources.json
  src/streaming/protection/drm/KeySystemPlayReady.js
  src/streaming/protection/models/ProtectionModel_21Jan2015.js
Labels: EME/DRM

#2900 Use CircleCI as our continuous build/deployment system
  .circleci/config.yml
  .travis.yml
Labels: Automation

#2894 Fix stall state management when not in low latency mode
  src/streaming/controllers/PlaybackController.js
Labels: Regression

#2899 Fix disabling of catchup (leave playback rate alone)
  src/streaming/controllers/PlaybackController.js
Labels: Regression
