Repository Dash-Industry-Forum/dash.js, pull requests merged in 2020-03, with the labels that each got.

#3195 fix: use fallback ID if Name is undefined
  src/mss/parser/MssParser.js
Labels: Bug, MSS

#3199 [Bug] SuggestedPresentationDelay is ignored because of wrong referenc…
  src/dash/models/DashManifestModel.js
  src/dash/parser/matchers/DurationMatcher.js
Labels: Bug

#3099 Add SegmentBaseController
  src/core/events/CoreEvents.js
  src/dash/DashHandler.js
  src/dash/SegmentBaseLoader.js
  src/dash/WebmSegmentBaseLoader.js
  src/dash/controllers/SegmentBaseController.js
  src/dash/controllers/SegmentsController.js
  src/streaming/MediaPlayer.js
  src/streaming/StreamProcessor.js
  src/streaming/thumbnail/ThumbnailTracks.js
  src/streaming/vo/FragmentRequest.js
  src/streaming/vo/HeadRequest.js
  test/unit/dash.SegmentBaseLoader.js
  test/unit/dash.WebSegmentBaseLoader.js
Labels: Code Refactor

#3102 DashMetrics
  index.d.ts
  src/dash/DashMetrics.js
  src/streaming/MediaPlayer.js
  src/streaming/controllers/AbrController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/models/CmcdModel.js
  src/streaming/rules/abr/AbandonRequestsRule.js
  src/streaming/rules/abr/BolaRule.js
  src/streaming/rules/abr/InsufficientBufferRule.js
  src/streaming/rules/abr/ThroughputRule.js
  src/streaming/rules/scheduling/BufferLevelRule.js
  test/unit/dash.DashMetrics.js
  test/unit/mocks/DashMetricsMock.js
Labels: Feature Enhancement

#3204 Bugfix functional tests mac
  test/functional/config/browsers/mac.js
  test/functional/readme.md
Labels: Functional Testing

#3206 Functional tests report
  .circleci/config.yml
  test/functional/config.js
  test/functional/config/applications.js
  test/functional/config/selenium.js
  test/functional/readme.md
  test/functional/tests/ended.js
  test/functional/tests/pause.js
  test/functional/tests/play.js
  test/functional/tests/playFromTime.js
  test/functional/tests/scripts/utils.js
  test/functional/tests/seek.js
  test/functional/tests/setup.js
Labels: Functional Testing

#3205 Restart ScheduleController once buffer is pruned only after QuotaExceedeError
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/ScheduleController.js
Labels: Bug

#3209 Compose streams looks for the right initial stream when playing dynam…
  src/streaming/controllers/StreamController.js
Labels: Multiperiod
