Repository Dash-Industry-Forum/dash.js, pull requests merged in 2020-06, with the labels that each got.

#3256 [Code refactoring] remove circular dependencies
  src/core/events/CoreEvents.js
  src/dash/DashMetrics.js
  src/dash/controllers/RepresentationController.js
  src/mss/MssHandler.js
  src/streaming/Stream.js
  src/streaming/StreamProcessor.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/controllers/StreamController.js
  src/streaming/rules/scheduling/BufferLevelRule.js
  src/streaming/text/NotFragmentedTextBufferController.js
  src/streaming/text/TextBufferController.js
  src/streaming/text/TextSourceBuffer.js
  test/unit/Streaming.StreamProcessor.js
  test/unit/mocks/AdapterMock.js
  test/unit/mocks/StreamProcessorMock.js
  test/unit/streaming.Stream.js
  test/unit/streaming.controllers.BufferController.js
  test/unit/streaming.controllers.ScheduleController.js
  test/unit/streaming.controllers.StreamController.js
  test/unit/streaming.rules.scheduling.BufferLevelRule.js
  test/unit/streaming.text.NotFragmentedTextBufferController.js
  test/unit/streaming.text.TextSourceBuffer.js
Labels: Code Refactor, Code Review Needed

#3278 Remove NextFragmentRequestRule
  src/streaming/rules/scheduling/NextFragmentRequestRule.js
  src/streaming/text/TextController.js
  test/unit/streaming.rules.scheduling.NextFragmentRequestRule.js
Labels: Code Refactor

#3277 Fix a bug which causes no calculation of live seek range in the MSE f…
  src/streaming/controllers/StreamController.js
Labels: Bug

#3245 allow setInitialMediaSettingsFor with fragmentedText media type
  samples/captioning/multi-track-captions.html
  samples/dash-if-reference-player/app/main.js
  samples/dash-if-reference-player/index.html
  src/streaming/MediaPlayer.js
  src/streaming/controllers/MediaController.js
  src/streaming/text/TextController.js
  test/unit/mocks/MediaControllerMock.js
  test/unit/streaming.MediaPlayer.js
  test/unit/streaming.text.TextController.js
Labels: Subtitles

#3282 [MSS] Restore default buffer settings
  src/mss/MssHandler.js
  src/mss/parser/MssParser.js
Labels: Bug, MSS

#3284 Fix regression for representationInfo's segmentDuration
  src/dash/controllers/RepresentationController.js
  src/streaming/StreamProcessor.js
Labels: Regression

#3285 Fix live delay computation
  src/dash/controllers/RepresentationController.js
  src/streaming/StreamProcessor.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/StreamController.js
  test/unit/streaming.controllers.PlaybackControllers.js
Labels: Bug

#3286 Fix regression with enableText
  samples/captioning/caption_vtt.html
  samples/captioning/multi-track-captions.html
  samples/captioning/ttml-ebutt-sample.html
  src/streaming/text/TextController.js
  test/unit/streaming.text.TextController.js
Labels: Regression

#3288 Update jsdoc
  src/streaming/net/SchemeLoaderFactory.js
  src/streaming/net/URLLoader.js
  src/streaming/utils/DefaultURLUtils.js
Labels: Documentation

#3298 Check if dvr window is finite before trying to find a request at the …
  src/streaming/StreamProcessor.js
Labels: Bug

#3299 [MSS] Set minBufferTime to one video segment duration
  src/mss/parser/MssParser.js
Labels: MSS

#3309 Fix moov duration fields
  src/mss/MssFragmentMoovProcessor.js
Labels: MSS

#3294 Segment availability range if no timeShiftBufferDepth
  src/dash/utils/TimelineConverter.js
Labels: Awaiting Feedback

#3316 Define a threshold which controls catchup mechanism for low latency streaming
  samples/dash-if-reference-player/dashjs_config.json
  src/core/Settings.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/models/MediaPlayerModel.js
  test/unit/streaming.models.MediaPlayerModel.js
Labels: Feature Enhancement

#3308 Refactor streams playback start
  src/streaming/Stream.js
  src/streaming/StreamProcessor.js
  src/streaming/controllers/BufferController.js
  src/streaming/controllers/PlaybackController.js
  src/streaming/controllers/ScheduleController.js
  src/streaming/controllers/StreamController.js
  src/streaming/text/NotFragmentedTextBufferController.js
  src/streaming/text/TextBufferController.js
  test/unit/streaming.controllers.PlaybackControllers.js
Labels: Code Refactor
