Repository Dash-Industry-Forum/dash.js, pull requests merged in 2020-01, with the labels that each got.

#3149 Update common earliest time management
  src/streaming/controllers/PlaybackController.js
Labels: Bug

#3143 Update buffer level metrics
  src/streaming/controllers/BufferController.js
Labels: Bug

#3162 Remove default value in typeScript
  index.d.ts
  src/streaming/protection/vo/ProtectionData.js
Labels: Bug

#3154 Fix Issue #3083 for live streams with multiperiod.
  src/dash/utils/SegmentsUtils.js
Labels: Bug, Multiperiod

#3164 update parseFloat call
  src/dash/parser/matchers/DurationMatcher.js
Labels: Code Refactor

#2866 feat capability to match lang regex for initial settings
  src/streaming/MediaPlayer.js
  src/streaming/controllers/MediaController.js
  test/unit/streaming.controllers.MediaController.js
Labels: Feature Enhancement
