Repository Dash-Industry-Forum/dash.js, pull requests merged in 2021-05, with the labels that each got.

#3642 Fix minor bugs
  src/streaming/controllers/AbrController.js
  src/streaming/controllers/MediaSourceController.js
Labels: Bug

#3643 Fix segmented text track selection
  src/streaming/text/TextController.js
Labels: Bug, Subtitles

#3635 Feature memory optimizations
  index.d.ts
  samples/dash-if-reference-player/app/main.js
  samples/offline/dashjs_config.json
  src/core/Settings.js
  src/dash/DashHandler.js
  src/dash/SegmentBaseLoader.js
  src/dash/utils/TimelineConverter.js
  src/mss/parser/MssParser.js
  src/streaming/SourceBufferSink.js
  src/streaming/Stream.js
  src/streaming/StreamProcessor.js
  src/streaming/constants/ConformanceViolationConstants.js
  src/streaming/controllers/EventController.js
  src/streaming/controllers/StreamController.js
  src/streaming/controllers/TimeSyncController.js
  src/streaming/models/MetricsModel.js
  test/unit/dash.utils.TimelineConverter.js
  test/unit/streaming.MediaPlayer.js
  test/unit/streaming.controllers.TimeSyncController.js
Labels: Work in Progress - Don't Merge
