Repository Dash-Industry-Forum/dash.js, pull requests merged in 2021-09, with the labels that each got.

#3746 [MSS] Fix availabilityTimeOffset for live MSS
  src/mss/parser/MssParser.js
Labels: Regression

#3749 [MSS] fix issue when selecting new audio track and new text track sim…
  src/streaming/Stream.js
Labels: Bug, MSS

#3751 Add track selection mode based on selectionPriority attribute
  index.d.ts
  src/core/Settings.js
  src/dash/DashAdapter.js
  src/dash/models/DashManifestModel.js
  src/dash/vo/MediaInfo.js
  src/streaming/constants/Constants.js
  src/streaming/controllers/MediaController.js
  test/unit/dash.models.DashManifestModel.js
  test/unit/streaming.controllers.MediaController.js
Labels: Feature request from DASH IF IOP

#3714 Test suite live delay
  test/functional/testSuites.js
  test/functional/tests/liveDelay.js
  test/functional/tests/play.js
  test/functional/tests/scripts/player.js
Labels: Functional Testing

#3779 Avoid creating one HTTPLoader instance per request
  src/streaming/net/URLLoader.js
Labels: Bug

#3780 [MSS] Do not update manifest if already updating at tracks switching for live streams
  src/streaming/ManifestUpdater.js
  src/streaming/Stream.js
Labels: MSS
